export const NAV_ITEMS = [
  { href: "/dashboard", label: "Dashboard", icon: "LayoutDashboard" },
  { href: "/transactions", label: "Transactions", icon: "ArrowLeftRight" },
  { href: "/tasks", label: "Tugas", icon: "ListTodo" },
  { href: "/notes", label: "Catatan", icon: "StickyNote" },
  { href: "/content", label: "Konten", icon: "Clapperboard" },
  { href: "/wallets", label: "Wallets", icon: "Wallet" },
  { href: "/budgets", label: "Budgets", icon: "Target" },
  { href: "/subscriptions", label: "Subscriptions", icon: "Repeat" },
  { href: "/forecast", label: "Forecast", icon: "TrendingUp" },
  { href: "/prayers", label: "Prayers", icon: "Moon" },
  { href: "/prayers/report", label: "Laporan Shalat", icon: "BarChart3" },
  { href: "/health", label: "Health", icon: "HeartPulse" },
  { href: "/food", label: "Food Log", icon: "Utensils" },
  { href: "/categories", label: "Categories", icon: "Tags" },
  { href: "/reports", label: "Reports", icon: "PieChart" },
  { href: "/settings", label: "Settings", icon: "Settings" },
] as const;
